<?php require('template/header.phtml') ?>

    <div class="container-fluid">
        <div id="boxModel" class="col-xs-12 col-sm-9 col-md-10">
            <h3>Browse</h3>


            <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                <div style="overflow-x:auto;">
                <table class="table table-xs-responsive">
                    <thead >
                    <tr>
                        <th>Advert Title</th><th>Advert Picture</th><th>Advert Description</th><th>Advert Price</th><th>Add To Watchlist</th>
                    </tr>
                    </thead>
                    <tbody>
<!--                    //This foreach lop allows the lop to go through the advert data set as $advertData, in which we can view after it has went,-->
<!--                    //though the lop it will echo out into each column from left to right filling in all the spaces. All the data comes from the,-->
<!--                    //advert data set/advert data.-->
                    <?php foreach ($view->advertDataSet as $advertData) {
                        echo '<tr> <td>' . $advertData->getAdvertTitle() . '</td> <td>' . '<img src="../images/'.$advertData->getAdvertPicture().'" id="browseImg" />' . '</td> <td>' . $advertData->getAdvertDescription() . '</td> <td>' . $advertData->getAdvertPrice() . '</td> <td>' . '<a href="Watchlist.php?id=' . $advertData->getAdvertId() . '" type="button" class="btn btn-primary">Add to watch list</a>' . '</td>   </tr>';
                    }
                    ?>
                    </tbody>
                </table>
                </div>
            </form>

        </div>
        </div>

<?php require('template/footer.phtml') ?>

