<?php require('template/header.phtml') ?>
<div class="container-fluid">
    <div id="boxModel" class="col-xs-12 col-sm-9 col-md-10">

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3">Welcome To Strike 28</h1>
            <p class="lead">A new website for selling and buying new shoes,from new to old <i>any shoe counts.</i></p>
            <a class="btn btn-primary" href="browse.php" role="button">Go search</a>

        </div>
    </div>


    </div>
</div>

<div class="container-fluid">
    <div id="boxModel" class="col-xs-12 col-sm-9 col-md-10">


    </div>
</div>



<?php require('template/footer.phtml') ?>
