<?php require('template/header.phtml') ?>

<h3>Post Advert</h3>





    <form method="POST" action="../postAdvert.php">
<!--        //This form allows you to enter specific data into the feilds and then allows you to post it into browser when,-->
<!--        //clicked on the submit button.-->
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input  class="form-control" id="inputTitle" placeholder="Title" name="advertTitle">
                <input type="file"  id="inputPicture" placeholder="Picture" name="advertPicture">
                <input  class="form-control" id="inputDesc" placeholder="Description" name="advertDescription">
                <input  class="form-control" id="inputPrice" placeholder="Price" name="advertPrice">
<!--                type="text"-->

            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" name="submit" value="submit" class="btn btn-primary">Post Advert</button>
            </div>
        </div>
    </form>




<?php require('template/footer.phtml') ?>